In [1]:
import pandas as pd



# Load the housing info CSV file into a pandas DF
housing_data = pd.read_csv('California_Housing_CitiesAdded.csv')

# Display the column names
print("Column Names:")
print(housing_data.columns)

# Display the first 10 rows of the DataFrame
print("\nFirst 10 rows:")
print(housing_data.head(10))

# Determine the total number of rows 
total_rows = housing_data.shape[0]
print(f"\nTotal number of rows in the dataset: {total_rows}")

Column Names:
Index(['Median_House_Value', 'Median_Income', 'Median_Age', 'Tot_Rooms',
       'Tot_Bedrooms', 'Population', 'Households', 'Latitude', 'Longitude',
       'Distance_to_coast', 'Distance_to_LA', 'Distance_to_SanDiego',
       'Distance_to_SanJose', 'Distance_to_SanFrancisco', 'ocean_proximity',
       'City'],
      dtype='object')

First 10 rows:
   Median_House_Value  Median_Income  Median_Age  Tot_Rooms  Tot_Bedrooms  \
0            500001.0         1.2434          52        249            78
1            500001.0         1.1696          52        609           236
2            500001.0         7.8521          52       1668           225
3            500001.0         9.3959          52       3726           474
4            500001.0         7.8772          52       2990           379
5            500001.0        11.8603          39       2492           310
6            500001.0        13.4990          42       2991           335
7            500001.0        12.2138          52       3242           366
8            500001.0        12.3804          52       3494           396
9            500001.0         8.7477          52       1611           203

   Population  Households  Latitude  Longitude  Distance_to_coast  \
0         396          85     37.80    -122.27        2524.614616
1        1349         250     37.87    -122.25        7897.024567
2         517         214     37.86    -122.24        9154.528309
3        1366         496     37.85    -122.24        8259.085109
4         947         361     37.83    -122.23        7284.913015
5         808         315     37.82    -122.22        7447.262038
6        1018         335     37.82    -122.22        7447.262038
7        1001         352     37.82    -122.23        6670.966116
8        1192         383     37.82    -122.23        6670.966116
9         556         179     37.82    -122.23        6670.966116

   Distance_to_LA  Distance_to_SanDiego  Distance_to_SanJose  \
0     552234.0515           731023.5749          61415.35211
1     556856.9280           735788.3723          67242.51828
2     555442.5086           734372.6023          65849.13943
3     554610.7171           733525.6829          64867.28983
4     552365.4712           731263.5682          62493.11252
5     550950.9605           729847.5883          61097.42739
6     550950.9605           729847.5883          61097.42739
7     551535.6797           730418.0382          61517.93721
8     551535.6797           730418.0382          61517.93721
9     551535.6797           730418.0382          61517.93721

   Distance_to_SanFrancisco ocean_proximity     City
0               14466.70538        NEAR BAY  Alameda
1               19172.81885        NEAR BAY  Alameda
2               19335.74118        NEAR BAY  Alameda
3               18811.48745        NEAR BAY  Alameda
4               18750.94628        NEAR BAY  Alameda
5               19258.11494        NEAR BAY  Alameda
6               19258.11494        NEAR BAY  Alameda
7               18412.54557        NEAR BAY  Alameda
8               18412.54557        NEAR BAY  Alameda
9               18412.54557        NEAR BAY  Alameda

Total number of rows in the dataset: 20640

In [4]:
import pandas as pd
# Load CSV
housing_data = pd.read_csv('California_Housing_CitiesAdded.csv')

# Get all the unique city names
unique_city_names = housing_data['City'].unique()


print("\nUnique city names:")
print(unique_city_names)

Unique city names:
['Alameda' 'Contra Costa' 'El Dorado' 'Los Angeles' 'Orange' 'Marin'
 'Monterey' 'Riverside' 'San Bernardino' 'San Diego' 'San Francisco'
 'San Luis Obispo' 'San Mateo' 'Santa Barbara' 'Santa Clara' 'Santa Cruz'
 'Ventura' 'San Joaquin' 'Stanislaus' 'Sacramento' 'Napa' 'Placer'
 'Solano' 'Sonoma' 'San Benito' 'Nevada' 'Fresno' 'Yolo' 'Mendocino'
 'Kern' 'Mono' 'Tulare' 'Kings' 'Sutter' 'Tuolumne' 'Merced' 'Lake'
 'Butte' 'Lassen' 'Amador' 'Inyo' 'Shasta' 'Humboldt' 'Yuba' 'Imperial'
 'Madera' 'Del Norte' 'Tehama' 'Calaveras' 'Plumas' 'Siskiyou' 'Glenn'
 'Colusa' 'Sierra' 'Modoc']

In [10]:
# we are only interested in seeing housing and median income info for the area within the relevant crime district
la_housing_data = housing_data[housing_data['City'] == 'Los Angeles']

# Display the filtered data
print("\nFiltered data for Los Angeles:")
print(la_housing_data)

# Save the filtered data to a new CSV (optional)
la_housing_data.to_csv('LA_Housing_Data_2.csv', index=False)

Filtered data for Los Angeles:
       Median_House_Value  Median_Income  Median_Age  Tot_Rooms  Tot_Bedrooms  \
28               500001.0        10.8805          10       7665           999
29               500001.0        10.9052          23       4960           592
30               500001.0         9.6047          20       7384           845
31               500001.0         8.5650          31       1962           243
32               500001.0         8.1714          23       2980           362
...                   ...            ...         ...        ...           ...
20223             55000.0         3.1415          19       1450           509
20224             55000.0         2.3000          45        543           191
20606             38800.0         1.9375          52        281           103
20635             17500.0         2.3667          39        493           168
20638             14999.0         4.1932          52        803           267

       Population  Households  Latitude  Longitude  Distance_to_coast  \
28           3517         998     34.28    -118.54        27774.13728
29           1929         586     34.26    -118.54        25596.69339
30           2795         872     34.27    -118.57        26263.89080
31            697         242     34.25    -118.56        24171.28565
32           1208         378     34.24    -118.56        23072.17475
...           ...         ...       ...        ...                ...
20223         746         437     34.03    -118.39        10800.68234
20224         454         181     34.14    -118.15        35526.59449
20606         470          96     34.02    -118.28        20782.07972
20635         259         138     34.15    -118.33        21926.83929
20638         628         225     34.24    -117.86        61064.66015

       Distance_to_LA  Distance_to_SanDiego  Distance_to_SanJose  \
28       37210.975340           215871.3204          454746.3628
29       35736.991790           214092.4277          456434.7298
30       38571.875590           216646.7724          453800.2264
31       36480.572930           214323.6214          456090.5958
32       35822.682410           213444.1903          456939.6905
...               ...                   ...                  ...
20223    13706.500690           185412.7641          484888.0714
20224    13025.075910           183036.6643          490199.3223
20606     4903.715482           178405.9703          492267.7273
20635    13466.357730           192870.4604          478320.2992
20638    41019.724230           181461.7572          500708.7456

       Distance_to_SanFrancisco ocean_proximity         City
28                  522763.9011       <1H OCEAN  Los Angeles
29                  524447.3710       <1H OCEAN  Los Angeles
30                  521807.6764       <1H OCEAN  Los Angeles
31                  524095.0103       <1H OCEAN  Los Angeles
32                  524941.0221       <1H OCEAN  Los Angeles
...                         ...             ...          ...
20223               552875.1070       <1H OCEAN  Los Angeles
20224               558231.1019       <1H OCEAN  Los Angeles
20606               560283.0656       <1H OCEAN  Los Angeles
20635               546350.0596       <1H OCEAN  Los Angeles
20638               568617.4593          INLAND  Los Angeles

[5836 rows x 16 columns]

In [11]:
# Count the number of na values in the median house value column
na_count = la_housing_data['Median_House_Value'].isna().sum()

print(f"\nNumber of missing values in 'Median_House_Value': {na_count}")

Number of missing values in 'Median_House_Value': 0

In [15]:
# categorizing the median home value column
bins = [0, 100000, 200000, 300000, 400000, 500000, float('inf')]
labels = ["< $100 thousand", ">= $100 thousand", ">= $200 thousand", ">= $300 thousand", ">= $400 thousand", ">= $Half Million"]
la_housing_data['Median_House_Value_Category'] = pd.cut(la_housing_data['Median_House_Value'], bins=bins, labels=labels)

# Display the filtered and categorized data
print("\nFiltered data for Los Angeles with categorized Median_House_Value:")
print(la_housing_data)

# Save the filtered data to a new CSV (optional)
la_housing_data.to_csv('LA_Housing_Data_Categorized_3.csv', index=False)

Filtered data for Los Angeles with categorized Median_House_Value:
       Median_House_Value  Median_Income  Median_Age  Tot_Rooms  Tot_Bedrooms  \
28               500001.0        10.8805          10       7665           999
29               500001.0        10.9052          23       4960           592
30               500001.0         9.6047          20       7384           845
31               500001.0         8.5650          31       1962           243
32               500001.0         8.1714          23       2980           362
...                   ...            ...         ...        ...           ...
20223             55000.0         3.1415          19       1450           509
20224             55000.0         2.3000          45        543           191
20606             38800.0         1.9375          52        281           103
20635             17500.0         2.3667          39        493           168
20638             14999.0         4.1932          52        803           267

       Population  Households  Latitude  Longitude  Distance_to_coast  \
28           3517         998     34.28    -118.54        27774.13728
29           1929         586     34.26    -118.54        25596.69339
30           2795         872     34.27    -118.57        26263.89080
31            697         242     34.25    -118.56        24171.28565
32           1208         378     34.24    -118.56        23072.17475
...           ...         ...       ...        ...                ...
20223         746         437     34.03    -118.39        10800.68234
20224         454         181     34.14    -118.15        35526.59449
20606         470          96     34.02    -118.28        20782.07972
20635         259         138     34.15    -118.33        21926.83929
20638         628         225     34.24    -117.86        61064.66015

       Distance_to_LA  Distance_to_SanDiego  Distance_to_SanJose  \
28       37210.975340           215871.3204          454746.3628
29       35736.991790           214092.4277          456434.7298
30       38571.875590           216646.7724          453800.2264
31       36480.572930           214323.6214          456090.5958
32       35822.682410           213444.1903          456939.6905
...               ...                   ...                  ...
20223    13706.500690           185412.7641          484888.0714
20224    13025.075910           183036.6643          490199.3223
20606     4903.715482           178405.9703          492267.7273
20635    13466.357730           192870.4604          478320.2992
20638    41019.724230           181461.7572          500708.7456

       Distance_to_SanFrancisco ocean_proximity         City  \
28                  522763.9011       <1H OCEAN  Los Angeles
29                  524447.3710       <1H OCEAN  Los Angeles
30                  521807.6764       <1H OCEAN  Los Angeles
31                  524095.0103       <1H OCEAN  Los Angeles
32                  524941.0221       <1H OCEAN  Los Angeles
...                         ...             ...          ...
20223               552875.1070       <1H OCEAN  Los Angeles
20224               558231.1019       <1H OCEAN  Los Angeles
20606               560283.0656       <1H OCEAN  Los Angeles
20635               546350.0596       <1H OCEAN  Los Angeles
20638               568617.4593          INLAND  Los Angeles

      Median_House_Value_Category
28               >= $Half Million
29               >= $Half Million
30               >= $Half Million
31               >= $Half Million
32               >= $Half Million
...                           ...
20223             < $100 thousand
20224             < $100 thousand
20606             < $100 thousand
20635             < $100 thousand
20638             < $100 thousand

[5836 rows x 17 columns]

C:\Users\John\AppData\Local\Temp\ipykernel_39692\1498360959.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  la_housing_data['Median_House_Value_Category'] = pd.cut(la_housing_data['Median_House_Value'], bins=bins, labels=labels)

In [17]:
housing_data_catted = pd.read_csv('LA_Housing_Data_Categorized_3.csv')

In [18]:
# Display the first 10 rows of the DataFrame
print("\nFirst 10 rows:")
print(housing_data_catted.head(10))

First 10 rows:
   Median_House_Value  Median_Income  Median_Age  Tot_Rooms  Tot_Bedrooms  \
0            500001.0        10.8805          10       7665           999
1            500001.0        10.9052          23       4960           592
2            500001.0         9.6047          20       7384           845
3            500001.0         8.5650          31       1962           243
4            500001.0         8.1714          23       2980           362
5            500001.0         8.8612          24       4338           558
6            500001.0         4.1544          35       2245           393
7            500001.0        11.2093          42        777           102
8            500001.0         9.6465           5       5429           665
9            500001.0         3.1875          31       1950           383

   Population  Households  Latitude  Longitude  Distance_to_coast  \
0        3517         998     34.28    -118.54        27774.13728
1        1929         586     34.26    -118.54        25596.69339
2        2795         872     34.27    -118.57        26263.89080
3         697         242     34.25    -118.56        24171.28565
4        1208         378     34.24    -118.56        23072.17475
5        1514         549     34.25    -118.51        25264.85008
6         783         402     34.15    -118.35        20601.01743
7         284         113     34.17    -118.43        18364.06680
8        2315         687     34.21    -118.65        20019.83690
9         870         357     34.17    -118.57        15242.98840

   Distance_to_LA  Distance_to_SanDiego  Distance_to_SanJose  \
0     37210.97534           215871.3204          454746.3628
1     35736.99179           214092.4277          456434.7298
2     38571.87559           216646.7724          453800.2264
3     36480.57293           214323.6214          456090.5958
4     35822.68241           213444.1903          456939.6905
5     32926.47514           211549.2698          459073.1678
6     14628.90845           193920.1480          477109.7452
7     21580.17167           200022.4657          470614.6307
8     41308.30439           216057.4366          454226.0575
9     32771.92359           207932.6733          462329.1622

   Distance_to_SanFrancisco ocean_proximity         City  \
0               522763.9011       <1H OCEAN  Los Angeles
1               524447.3710       <1H OCEAN  Los Angeles
2               521807.6764       <1H OCEAN  Los Angeles
3               524095.0103       <1H OCEAN  Los Angeles
4               524941.0221       <1H OCEAN  Los Angeles
5               527090.4176       <1H OCEAN  Los Angeles
6               545136.9364       <1H OCEAN  Los Angeles
7               538631.1559       <1H OCEAN  Los Angeles
8               522179.7825       <1H OCEAN  Los Angeles
9               530301.0635       <1H OCEAN  Los Angeles

  Median_House_Value_Category
0            >= $Half Million
1            >= $Half Million
2            >= $Half Million
3            >= $Half Million
4            >= $Half Million
5            >= $Half Million
6            >= $Half Million
7            >= $Half Million
8            >= $Half Million
9            >= $Half Million

In [19]:
print(housing_data_catted.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5836 entries, 0 to 5835
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Median_House_Value           5836 non-null   float64
 1   Median_Income                5836 non-null   float64
 2   Median_Age                   5836 non-null   int64
 3   Tot_Rooms                    5836 non-null   int64
 4   Tot_Bedrooms                 5836 non-null   int64
 5   Population                   5836 non-null   int64
 6   Households                   5836 non-null   int64
 7   Latitude                     5836 non-null   float64
 8   Longitude                    5836 non-null   float64
 9   Distance_to_coast            5836 non-null   float64
 10  Distance_to_LA               5836 non-null   float64
 11  Distance_to_SanDiego         5836 non-null   float64
 12  Distance_to_SanJose          5836 non-null   float64
 13  Distance_to_SanFrancisco     5836 non-null   float64
 14  ocean_proximity              5836 non-null   object
 15  City                         5836 non-null   object
 16  Median_House_Value_Category  5836 non-null   object
dtypes: float64(9), int64(5), object(3)
memory usage: 775.2+ KB
None